### ISSUE TITLE
Please consider dual-licensing under MIT + Apache License

### ISSUE THREAD

**Issue by amodm** [Brendonovich/swift-rs#15]
The rest of the ecosystem mostly uses dual licensing under MIT + Apache, and so does [the Rust project](https://www.rust-lang.org/policies/licenses). See [this issue](https://github.com/sfackler/rust-postgres-macros/issues/19) as an example, and for steps on how to do it.

Should you choose to do it, you have the permission from me: `I license past and future contributions to this project under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.`

**Comment by Brendonovich** [comment]
I'm down to do this, just need @0rvar and @haydenstith to approve it. Other contributors haven't made significant enough changes to require approval.

**Comment by 0rvar** [comment]
I approve

**Comment by haydenstith** [comment]
I approve of my contributions being dual licensed
