### ISSUE TITLE
Decrement ARC counts on SRObject drop

### ISSUE THREAD

**Issue by Brendonovich** [Brendonovich/swift-rs#2]
After looking over swift-bindgen's code, it seems that it's [possible](https://github.com/nvzqz/swift-bindgen/blob/main/swift-sys/src/heap/fns.rs) to manually alter ARC counts for arbitrary pointers, meaning that it should be possible to let the swift runtime know when rust is done with an SRObject by decrementing the corresponding ARC. This should avoid memory leaks that I believe exist at the moment, since I don't thing swift knows when rust is finished with a value.

**Comment by Brendonovich** [comment]
Did some testing and it doesn't seem like this is possible

**Comment by 0rvar** [comment]
@Brendonovich did you figure out how to release memory from the Rust side?

**Comment by Brendonovich** [comment]
@0rvar No, I wasn't able to figure it out. I was able to call the release and retain functions, but often the retain count of objects would be in the thousands and I had no idea why. No matter what I tried, dropping an SRObject wouldn't trigger the corresponding Swift object's deinit(). Would be great to figure it out but I'm not sure I want to try again haha.

**Comment by Brendonovich** [comment]
@0rvar My curiosity got the better of me and I tried a different approach for doing retains and releases: Instead of doing so via those Rust bindings, I defined functions on the Swift side that use `Unmanaged.passUnretained` to retain and release objects at will, and to my surprise it works! I'm able to have this swift binding:
```swift
@_cdecl("decrease_retain_count")
public func decreaseRetainCount(obj: UnsafePointer<AnyObject>) {
    let _ = Unmanaged.passUnretained(obj.pointee).release();
}
```

and call it like this:

```rust
extern "C" {
    fn decrease_retain_count(obj: &SRString);
}

impl Drop for SRString {
    fn drop(&mut self) {
        unsafe { decrease_retain_count(&self) }
        
        println!("Dropped SRString");
    }
}
```

Works just as I'd expect, printing the Drop message _as well as_ the deinit() message! Knowing this I may just do a bit of a rewrite and give this library some much needed attention.

**Comment by 0rvar** [comment]
@Brendonovich I've upgraded to latest master, but still getting memory leaking. I'll create a branch reproducing the leaks I get.

**Comment by Brendonovich** [comment]
@0rvar That's interesting. I haven't actually been measuring for memory leaks only checking that objects are being released properly. Building your example without the final loop, navigating to the executable's folder and running `leaks -atExit -- ./example` results in the output `0 leaks for 0 total leaked bytes`. What are you using to measure the leaks?

**Comment by Brendonovich** [comment]
@0rvar Hmm, Instruments doesn't report anything wrong for some reason. I did the loop for 30000 iterations and then paused to allow for swift to potentially deallocate stuff but nope it just stays there. No idea why this would be happening
<img width="1383" alt="image" src="https://user-images.githubusercontent.com/14191578/159767995-6951f2a9-9ffe-440d-85e9-2c54f2b825bb.png">

**Comment by Brendonovich** [comment]
Interestingly, if the function called in the loop is made to just return a big `SRString`, then no continuous climb of memory usage occurs.
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/14191578/159771961-089fdf9e-bbc7-49bd-87ce-2ef673e43e50.png">
Additionally, in the `get_mounts` loop, Instruments reports that `Volume`, `SRArray`, etc are actually being destroyed:
<img width="711" alt="image" src="https://user-images.githubusercontent.com/14191578/159772828-8c1c18dc-5d20-4c7e-9cc5-670456740e16.png">
<img width="718" alt="image" src="https://user-images.githubusercontent.com/14191578/159773043-0e244ed8-1126-41f8-8d1c-7e818b3fe273.png">
Hence, I don't think this is a problem with the deallocation, but rather with how the process of fetching the mounts works - and maybe there's a memory leak within it.

And it turns out that yep, that was the problem. Calling `mountedVolumeURLs` was caching data, so wrapping it in an `autoreleasepool` fixed a lot of the leaks. Additionally, the for loop that iterates each url had to be wrapped in an `autoreleasepool` to allow swift to do cleanups between iterations, which fixed the last of the leaks. Now `swift-rs` definitely deallocates properly and I know more about writing Swift!
