### ISSUE TITLE
Retrigger build script when swift files modified

### ISSUE THREAD

**Issue by Brendonovich** [Brendonovich/swift-rs#28]

**Comment by cbyrneee** [comment]
We can probably use [`cargo:rerun-if-changed`](https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorerun-if-changedpath).

Unfortunately, you can't pass a directory:
> If the path points to a directory, it will scan the entire directory for any modifications.

But iterating over all of the files in the `path` provided when `with_package` is called, and printing the following for each one could suffice:
```rs
println!("cargo:rerun-if-changed={}", path);
```
