### ISSUE TITLE
Force using system clang

### ISSUE THREAD

**Issue by lucasfernog** [Brendonovich/swift-rs#50]
We're currently spawning the `clang` command [here](https://github.com/Brendonovich/swift-rs/blob/973c22215734d1d5b97c496601d658371e537ece/src-rs/build.rs#L299). If the PATH is modified (mine was `export PATH="/opt/homebrew/opt/llvm/bin:$PATH"`, `clang` will actually point to a different version of clang which does not include `libclang_rt.ios.a` or `libclang_rt.iossim.a`.

What do you think about changing `Command::new("clang")` to `Command::new("/usr/bin/clang")` so it always use the clang we're expecting?

**Comment by Brendonovich** [comment]
Idk anything about this but if we can guarantee that `/usr/bin/clang` always exists then this sounds fine
