### ISSUE TITLE
repo can't be depended on in new swift projects

### ISSUE THREAD

**Issue by devsnek** [Brendonovich/swift-rs#53]
i'm pretty unfamiliar with the swift ecosystem but from what i can tell, `package(name:url:from:)` delegates to `package(url:from:)` because it is deprecated, and `package(url:from:)` thinks that the name is `swift-rs`, while the actual name is `SwiftRs`. this means it can't be depended on at all. I tested this by creating a fork named `SwiftRs` which i was successfully able to depend on.

**Comment by Brendonovich** [comment]
Have you tried explicitly adding `SwiftRs` as a dependency of your target?
```rust
let package = Package(
    dependencies: [
        .package(url: "https://github.com/Brendonovich/swift-rs", from: "1.0.5")
    ],
    targets: [
        .target(
            dependencies: [
                .product(
                    name: "SwiftRs",
                    package: "swift-rs"
                )
            ]
        )
    ]
)
```

**Comment by devsnek** [comment]
ah, the `package: "swift-rs"` seems to have been what i was missing, thank you!

**Comment by Brendonovich** [comment]
Interesting, I'll update the docs accordingly.
